/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assessment20230825;

import assessment20230825.command.Command;
import assessment20230825.command.CommandsActionEnum;
import assessment20230825.exceptions.AppException;
import assessment20230825.queue.QueueService;
import assessment20230825.user.UserTableService;
import lombok.extern.log4j.Log4j2;

/** Queue app */
@Log4j2
public class QueueApp {
  public static void main(String[] args) throws AppException {
    log.info("Starting queue app");
    // init database
    UserTableService.getInstance().createTable();

    // init queue service
    QueueService queueServiceStart = QueueService.getInstance();

    // perform demonstration test case
    queueServiceStart.addCommand(new Command("(1, \"a1\", \"Robert\")"));
    queueServiceStart.addCommand(new Command("(2, \"a2\", \"Martin\")"));
    queueServiceStart.addCommand(new Command(CommandsActionEnum.PRINT_ALL.supportValue));
    queueServiceStart.addCommand(new Command(CommandsActionEnum.DELETE_ALL.supportValue));
    queueServiceStart.addCommand(new Command(CommandsActionEnum.PRINT_ALL.supportValue));

    // send exit command to all consumers
    for (int i = 0; i < QueueService.CONSUMER_COUNT; i++) {
      queueServiceStart.addCommand(new Command(CommandsActionEnum.EXIT.name()));
    }
    // shutdown consumers gracefully
    queueServiceStart.shutdown();

    // clean up database
    UserTableService.getInstance().dropTable();

    log.info("Queue app exiting");
    System.exit(0);
  }
}
